In [19]:
import pandas as pd

dfP=pd.read_csv('datos.csv')
dfv=pd.read_csv('vivienda.csv')

# merge dataframes based on id column
dfd = pd.merge(dfv, dfP, on='FOLIO', how='inner')

print(dfd.head(10))

   FOLIO  P1_1  P1_2_1  P1_2_2  P1_3  P1_4_1  P1_4_2  P1_4_3  P1_4_4  P1_4_5  \
0      2     4       2       2     1     1.0     1.0     1.0     1.0     1.0   
1      2     4       2       2     1     1.0     1.0     1.0     1.0     1.0   
2      7     7       3       4     1     2.0     2.0     1.0     2.0     1.0   
3      7     7       3       4     1     2.0     2.0     1.0     2.0     1.0   
4      9     5       3       2     1     1.0     1.0     1.0     1.0     1.0   
5     11     4       2       2     1     1.0     1.0     1.0     2.0     1.0   
6     14     5       3       2     1     2.0     1.0     1.0     1.0     1.0   
7     14     5       3       2     1     2.0     1.0     1.0     1.0     1.0   
8     14     5       3       2     1     2.0     1.0     1.0     1.0     1.0   
9     15     4       2       2     1     2.0     1.0     2.0     2.0     1.0   

   ...  PD3_1  PD3_2  PD3_3  ENT_y  NIVEL_A  GRADO_A  NIVEL_B  GRADO_B  ESC  \
0  ...    NaN    NaN    NaN     24      

In [20]:
#dfd = dfd.dropna(thresh=dfd.shape[1]-15)
values_nivel=[1,2,3,10,11,12] 
values_nivel2=[1,2,9,10,11]
dfd=dfd[dfd.PA3_3_NIVEL.isin(values_nivel)==False] #quitamos los rows de los que van en kínder y primaria
dfd=dfd[dfd.PA3_3_MODMAT!=1] #quitamos los rows de los que estuvieron en maternal
dfd=dfd[dfd.PB3_5_MODMAT!=1] #quitamos los rows de los que se inscribieron a maternal
dfd=dfd[dfd.PB3_5_NIVEL.isin(values_nivel2)==False]#quitamos a los que se inscribieron al kinder y a los que se inscribieron a maestría/doctorado
dfd=dfd[dfd.PC3_1!=2]
values_c=[1,2,5,6,7,8,9,10,11,12,13,14] #quitamos los que por motivos personales no se inscribieron
dfd=dfd[dfd.PC3_6.isin(values_c)==False]
#dfd=dfd[dfd.FILTRO_C!=1] #Quitamos a los que no estuvieron inscritos en el anterior ni en el siguiente
dfd=dfd[dfd.PA3_6!=4]

dfd.drop(columns=['PA3_3_MODMAT','PB3_5_MODMAT','FOLIO'],inplace=True)
dfd['FILTRO_A']=dfd['FILTRO_A'].fillna(0) #SE CAMBIÓ DE ESCUELA
dfd['FILTRO_B']=dfd['FILTRO_B'].fillna(0) #MENORES DE 17?
dfd['FILTRO_C']=dfd['FILTRO_C'].fillna(0) #ABANDONO ESCOLAR?
dfd['PA3_5']=dfd['PA3_5'].fillna(0) #razones por las que no concluyó
dfd['PB3_4']=dfd['PB3_4'].fillna(0) #RAZPON POR LA QUE SE CAMBIÓ DE ESCUELA
dfd[['PA3_3_NIVEL','PB3_5_NIVEL','PA3_3_BIMESTRE','PA3_3_TRIMESTRE','PA3_3_CUATRIMESTRE','PA3_3_SEMESTRE','PA3_3_ANIO','PB3_5_BIMESTRE','PB3_5_TRIMESTRE','PB3_5_CUATRIMESTRE','PB3_5_SEMESTRE','PB3_5_ANIO']]=dfd[['PA3_3_NIVEL','PB3_5_NIVEL','PA3_3_BIMESTRE','PA3_3_TRIMESTRE','PA3_3_CUATRIMESTRE','PA3_3_SEMESTRE','PA3_3_ANIO','PB3_5_BIMESTRE','PB3_5_TRIMESTRE','PB3_5_CUATRIMESTRE','PB3_5_SEMESTRE','PB3_5_ANIO']].fillna(0)
dfd=dfd.fillna('NaN')


In [21]:
dfd.drop(columns=['P3_2'],inplace=True)

In [22]:
a=dfd['PA3_6'].to_numpy()
b=dfd['PA3_7_2'].to_numpy()
c=dfd['PA3_7_3'].to_numpy()
d=dfd['PA3_4'].to_numpy() #SON LOS QUE NO TERMINARON EL AÑO POR BAJO DESEMPEÑO
e=dfd['PB3_2'].to_numpy() #DEJAMOS LOS QUE RESPONDIERON QUE YA NO SE INSCRIBIERON AL SIGUIENTE POR BAJO DESEMPEÑO
f=dfd['PC3_6'].to_numpy() #los que dejaron la escuela porque tuvieron bajo desempeño
#dfd.drop(columns=['PA3_6','PA3_7_2','PA3_7_3','PA3_4','PB3_2'],inplace=True)
print(d.shape[0])
dfd.drop(columns=['PB3_7','PB3_8'],inplace=True) #QUITAMOS ESTAS DOS PORQUE LES FALTA LA MITAD DE LA DATA
#EN ESTAS DOS de arriba PREGUNTABAN CUÁNTOS DÍAS VAN A LA ESCUEL Y POR QUÉ
dfd.drop(columns=['NIVEL_A','GRADO_A','NIVEL_B','GRADO_B','ENT_y'],inplace=True)#estas preguntas estaban repetidas
dfd.drop(columns=['FACTOR_x','FACTOR_y','N_REN'],inplace=True) #ESTAS COLUMNAS NO SE SABE QUÉ SON, NO LO INDICARON EN EL CATÁLOGO


14663


In [23]:
import numpy as np
total=d.shape[0]
clase=np.zeros(total)
contador =0
contadornans=0
for i in range(total):
    if a[i]==1 or a[i]==2:
        clase[i]=1
        
    elif b[i]==1:
        clase[i]=1
        
    elif c[i]==1:
        clase[i]=1
        
    elif d[i]==2:
        clase[i]=1
        
    elif e[i]==3 or e[i]==5:
        
        clase[i]=1
    elif f[i]==3 or f[i]==4:
        clase[i]=1
    elif a[i]==b[i]==c[i]==d[i]==e[i]==f[i]=='NaN':
        clase[i]='NaN'
        contadornans+=1
    else:
        clase[i]=0
    

print(sum(clase),contadornans)
dfd.insert(0,'clase',clase)



nan 2433


In [24]:

dfd['PB3_4'] = dfd['PB3_4'].fillna(0) #los que se cambiaron de escuela
#porque a los mayores de 17 ya no les preguntaron las siguientes (las de si los ayudan los papás)
dfd.loc[dfd['EDAD'] >= 17, 'PB3_13_7'] = 0
dfd.loc[dfd['EDAD'] >= 17, 'PB3_13_6'] = 0
dfd.loc[dfd['EDAD'] >= 17, 'PB3_13_5'] = 0
dfd.loc[dfd['EDAD'] >= 17, 'PB3_13_4'] = 0
dfd.loc[dfd['EDAD'] >= 17, 'PB3_13_3'] = 0
dfd.loc[dfd['EDAD'] >= 17, 'PB3_13_2'] = 0
dfd.loc[dfd['EDAD'] >= 17, 'PB3_13_1'] = 0
dfd.loc[dfd['EDAD'] >= 17, 'PB3_14'] = 0
dfd.loc[dfd['EDAD'] >= 17, 'PB3_15'] = 0

#LOS QUE NO CUMPLEN CON EL FILTRO C, O SEA QUE SI ESTUVIERON INSCRITOS EN EL ANTERIOR Y SIGUEINTE
dfd.loc[dfd['FILTRO_C']==0,['PC3_1','PC3_2','PC3_3_1','PC3_3_2','PC3_4','PC3_5','PC3_6','PC3_7','PC3_8']]=0
dfd.loc[dfd['FILTRO_C']=='NaN',['PC3_1','PC3_2','PC3_3_1','PC3_3_2','PC3_4','PC3_5','PC3_6','PC3_7','PC3_8']]=0
#PARA LOS QUE RETOMARÁN LA ESCUELA
dfd.loc[dfd['FILTRO_C']==2,['PC3_1','PC3_3_1','PC3_3_2','PC3_4','PC3_5','PC3_6','PC3_7']]=0

#PARA LOS QUE RESPONDIERON QUE NO TRABAJAN, LAS OTRAS PREGUNTAS NO APLICAN
dfd.loc[dfd['FILTRO_D']==2,['PD3_1','PD3_2','PD3_3']]=0
dfd.loc[(dfd['FILTRO_D']=='NaN') & (dfd['EDAD']<=14),['PD3_1','PD3_2','PD3_3']]=0






In [25]:
print(dfd.head(10))

    clase  P1_1  P1_2_1  P1_2_2  P1_3  P1_4_1  P1_4_2  P1_4_3  P1_4_4  P1_4_5  \
1     0.0     4       2       2     1     1.0     1.0     1.0     1.0     1.0   
3     1.0     7       3       4     1     2.0     2.0     1.0     2.0     1.0   
4     0.0     5       3       2     1     1.0     1.0     1.0     1.0     1.0   
8     0.0     5       3       2     1     2.0     1.0     1.0     1.0     1.0   
9     0.0     4       2       2     1     2.0     1.0     2.0     2.0     1.0   
10    0.0     4       2       2     1     2.0     1.0     2.0     2.0     1.0   
11    NaN     5       1       4     1     2.0     1.0     1.0     2.0     1.0   
12    0.0     5       1       4     1     2.0     1.0     1.0     2.0     1.0   
14    0.0     7       4       3     1     2.0     1.0     1.0     1.0     1.0   
15    0.0     7       4       3     1     2.0     1.0     1.0     1.0     1.0   

    ...  PC3_5  PC3_6  PC3_7  PC3_8  FILTRO_D  PD3_1  PD3_2  PD3_3  ESC PC3_2  
1   ...      0      0      0

In [26]:
grupos=dfd.groupby(['clase'])


d1=pd.DataFrame(grupos.get_group(1))

d2=pd.DataFrame(grupos.get_group(0))
print(d1.shape[0],d2.shape[0])

#rellenamos los valores faltantes donde preguntan si le ayudaron.
#si respondieron que nadie les ayuda, rellenamos con un 2 las otras preguntas
d1.loc[d1['PB3_13_7'] == 1, 'PB3_13_6'] = 2
d1.loc[d1['PB3_13_7'] == 1, 'PB3_13_5'] = 2
d1.loc[d1['PB3_13_7'] == 1, 'PB3_13_4'] = 2
d1.loc[d1['PB3_13_7'] == 1, 'PB3_13_3'] = 2
d1.loc[d1['PB3_13_7'] == 1, 'PB3_13_2'] = 2
d1.loc[d1['PB3_13_7'] == 1, 'PB3_13_1'] = 2

#para los que no concluyeron en algunos casos ya no preguntaron sobre los featues que seguían

###################################################################################
#####################################################################################
######################################################################################
#POR SI NO PREGUNTARON A LOS QUE NO CONCLUYERON LAS PARTES DE COMO SE INGRESA A LA ESCUELA
d1.loc[d1['PA3_4']==2,'PB3_6']=0 #asistía a presencial ono?
d1.loc[d1['PA3_4']==2,'PB3_3']=0 #la escuela es privada o no?
d1.loc[d1['PA3_4']==2,'PA3_7_1']=0 #RECIBIÓ ASESORÍAS EXTRA?
d1.loc[d1['PA3_4']==2,'PA3_2']=0 #PRIVADA?
#METODOS DE EVALUACIÓN
d1.loc[(d1['PA3_4']==2),
       #(d1['PA3_8_1']=='NaN')&
       #(d1['PA3_8_2']=='NaN')&
       #(d1['PA3_8_3']=='NaN')&
       #(d1['PA3_8_5']=='Nan')&
       #(d1['PA3_8_6']=='NaN')&
       #(d1['PA3_8_7']=='NaN')&
       #(d1['PA3_8_8']=='NaN'),
       ['PA3_8_1','PA3_8_2','PA3_8_3','PA3_8_4','PA3_8_5','PA3_8_6','PA3_8_7','PA3_8_8']]=0


#PREGUNTAS SOBRE METODOS DE INGRESO A LA ESCUELA
d1.loc[(d1['PA3_4']==2)&
       (d1['PB3_9_1']=='NaN')&
       (d1['PB3_9_2']=='NaN')&
       (d1['PB3_9_3']=='NaN'),
       ['PB3_9_1','PB3_9_2','PB3_9_3']]=0

#MATERIAL QUE USAN SUS MAESTROS
d1.loc[(d1['PA3_4']==2)&
       (d1['PB3_10_1']=='NaN')&
       (d1['PB3_10_2']=='NaN')&
       (d1['PB3_10_3']=='NaN')&
       (d1['PB3_10_4']=='NaN')&
       (d1['PB3_10_5']=='NaN'),
       ['PB3_10_1','PB3_10_2','PB3_10_3','PB3_10_4','PB3_10_5']]=0

#MEDIOS PARA INFORMARLE DE SUS TAREAS
d1.loc[(d1['PA3_4']==2)&
       (d1['PB3_11_1']=='NaN')&
       (d1['PB3_11_2']=='NaN')&
       (d1['PB3_11_3']=='NaN')&
       (d1['PB3_11_4']=='NaN')&
       (d1['PB3_11_5']=='NaN'),
       ['PB3_11_1','PB3_11_2','PB3_11_3','PB3_11_4','PB3_11_5']]=0

#MATERIALES QUE USA PARA SUS TAREAS
d1.loc[(d1['PA3_4']==2)&
       (d1['PB3_12_1']=='NaN')&
       (d1['PB3_12_2']=='NaN')&
       (d1['PB3_12_3']=='NaN')&
       (d1['PB3_12_4']=='NaN')&
       (d1['PB3_12_5']=='NaN')&
       (d1['PB3_12_6']=='NaN')&
       (d1['PB3_12_7']=='NaN')&
       (d1['PB3_12_8']=='NaN'),
       ['PB3_12_1','PB3_12_2','PB3_12_3','PB3_12_4','PB3_12_5','PB3_12_6','PB3_12_7','PB3_12_8']]=0

#¿LA PERSONA RECIBIO AYUDA de la familia?
d1.loc[(d1['PA3_4']==2) &
       (d1['PB3_13_1']=='NaN')&
       (d1['PB3_13_2']=='NaN')&
       (d1['PB3_13_3']=='NaN')&
       (d1['PB3_13_4']=='NaN')&
       (d1['PB3_13_5']=='NaN')&
       (d1['PB3_13_6']=='NaN')&
       (d1['PB3_13_7']=='NaN')&
       (d1['PB3_15']=='NaN')&
       (d1['PB3_14']=='NaN'),
       ['PB3_13_1','PB3_13_2','PB3_13_3','PB3_13_4','PB3_13_5','PB3_13_6','PB3_13_7','PB3_14','PB3_15']]=0

#¿cómo se siente de salud la persona?

d1.loc[(d1['PA3_4']==2)&
       (d1['PB3_16_1']=='NaN')&
       (d1['PB3_16_2']=='NaN')&
       (d1['PB3_16_3']=='NaN')&
       (d1['PB3_16_4']=='NaN')&
       (d1['PB3_16_5']=='NaN'),
       ['PB3_16_1','PB3_16_2','PB3_16_3','PB3_16_4','PB3_16_5']]=0

#####################################################################################################
#################################################################################################
###################################################################################################
d1.loc[d1['FILTRO_C']==1,'PA3_2']=0 #la escuela es privada o no
d1.loc[d1['FILTRO_C']==1,'PB3_3']=0 #la escuela es privada o no?
d1.loc[d1['FILTRO_C']==1,'PB3_6']=0 #asiste a presencial ono?
d1.loc[d1['FILTRO_C']==1,'PC3_8']=0 
d1.loc[d1['FILTRO_C']==1,'PA3_7_1']=0 #RECIBIÓ ASESORÍAS EXTRA?
#METODOS DE EVALUACIÓN
d1.loc[(d1['FILTRO_C']==1),
       #(d1['PA3_8_1']=='NaN')&
       #(d1['PA3_8_2']=='NaN')&
       #(d1['PA3_8_3']=='NaN')&
       #(d1['PA3_8_5']=='Nan')&
       #(d1['PA3_8_6']=='NaN')&
       #(d1['PA3_8_7']=='NaN')&
       #(d1['PA3_8_8']=='NaN'),
       ['PA3_8_1','PA3_8_2','PA3_8_3','PA3_8_4','PA3_8_5','PA3_8_6','PA3_8_7','PA3_8_8']]=0


#PREGUNTAS SOBRE METODOS DE INGRESO A LA ESCUELA
d1.loc[(d1['FILTRO_C']==1) &
       (d1['PB3_9_1']=='NaN')&
       (d1['PB3_9_2']=='NaN')&
       (d1['PB3_9_3']=='NaN'),
       ['PB3_9_1','PB3_9_2','PB3_9_3']]=0

#MATERIAL QUE USAN SUS MAESTROS
d1.loc[(d1['FILTRO_C']==1) &
       (d1['PB3_10_1']=='NaN')&
       (d1['PB3_10_2']=='NaN')&
       (d1['PB3_10_3']=='NaN')&
       (d1['PB3_10_4']=='NaN')&
       (d1['PB3_10_5']=='NaN'),
       ['PB3_10_1','PB3_10_2','PB3_10_3','PB3_10_4','PB3_10_5']]=0

#MEDIOS PARA INFORMARLE DE SUS TAREAS
d1.loc[(d1['FILTRO_C']==1)&
       (d1['PB3_11_1']=='NaN')&
       (d1['PB3_11_2']=='NaN')&
       (d1['PB3_11_3']=='NaN')&
       (d1['PB3_11_4']=='NaN')&
       (d1['PB3_11_5']=='NaN'),
       ['PB3_11_1','PB3_11_2','PB3_11_3','PB3_11_4','PB3_11_5']]=0

#MATERIALES QUE USA PARA SUS TAREAS
d1.loc[(d1['FILTRO_C']==1)&
       (d1['PB3_12_1']=='NaN')&
       (d1['PB3_12_2']=='NaN')&
       (d1['PB3_12_3']=='NaN')&
       (d1['PB3_12_4']=='NaN')&
       (d1['PB3_12_5']=='NaN')&
       (d1['PB3_12_6']=='NaN')&
       (d1['PB3_12_7']=='NaN')&
       (d1['PB3_12_8']=='NaN'),
       ['PB3_12_1','PB3_12_2','PB3_12_3','PB3_12_4','PB3_12_5','PB3_12_6','PB3_12_7','PB3_12_8']]=0

#¿LA PERSONA RECIBIO AYUDA de la familia?
d1.loc[(d1['FILTRO_C']==1) &
       (d1['PB3_13_1']=='NaN')&
       (d1['PB3_13_2']=='NaN')&
       (d1['PB3_13_3']=='NaN')&
       (d1['PB3_13_4']=='NaN')&
       (d1['PB3_13_5']=='NaN')&
       (d1['PB3_13_6']=='NaN')&
       (d1['PB3_13_7']=='NaN')&
       (d1['PB3_15']=='NaN')&
       (d1['PB3_14']=='NaN'),
       ['PB3_13_1','PB3_13_2','PB3_13_3','PB3_13_4','PB3_13_5','PB3_13_6','PB3_13_7','PB3_14','PB3_15']]=0

#¿cómo se siente de salud la persona?

d1.loc[(d1['FILTRO_C']==1)&
       (d1['PB3_16_1']=='NaN')&
       (d1['PB3_16_2']=='NaN')&
       (d1['PB3_16_3']=='NaN')&
       (d1['PB3_16_4']=='NaN')&
       (d1['PB3_16_5']=='NaN'),
       ['PB3_16_1','PB3_16_2','PB3_16_3','PB3_16_4','PB3_16_5']]=0

###################################################################################
#####################################################################################
######################################################################################
#METODOS DE EVALUACIÓN
d1.loc[d1['FILTRO_C']==2,'PA3_2']=0 #la escuela es privada o no?
d1.loc[d1['FILTRO_C']==2,'PB3_3']=0 #la escuela es privada o no?
d1.loc[d1['FILTRO_C']==2,'PA3_7_1']=0 #RECIBIÓ ASESORÍAS EXTRA?
d1.loc[d1['FILTRO_C']==2,'PB3_6']=0 #asiste a presencial o no?

d1.loc[(d1['FILTRO_C']==2)&
       (d1['PA3_8_1']=='NaN')&
       (d1['PA3_8_2']=='NaN')&
       (d1['PA3_8_3']=='NaN')&
       (d1['PA3_8_5']=='Nan')&
       (d1['PA3_8_6']=='NaN')&
       (d1['PA3_8_7']=='NaN')&
       (d1['PA3_8_8']=='NaN'),
       ['PA3_8_1','PA3_8_2','PA3_8_3','PA3_8_4','PA3_8_5','PA3_8_6','PA3_8_7','PA3_8_8']]=0


#PREGUNTAS SOBRE METODOS DE INGRESO A LA ESCUELA
d1.loc[(d1['FILTRO_C']==2) &
       (d1['PB3_9_1']=='NaN')&
       (d1['PB3_9_2']=='NaN')&
       (d1['PB3_9_3']=='NaN'),
       ['PB3_9_1','PB3_9_2','PB3_9_3']]=0

#MATERIAL QUE USAN SUS MAESTROS
d1.loc[(d1['FILTRO_C']==2) &
       (d1['PB3_10_1']=='NaN')&
       (d1['PB3_10_2']=='NaN')&
       (d1['PB3_10_3']=='NaN')&
       (d1['PB3_10_4']=='NaN')&
       (d1['PB3_10_5']=='NaN'),
       ['PB3_10_1','PB3_10_2','PB3_10_3','PB3_10_4','PB3_10_5']]=0

#MEDIOS PARA INFORMARLE DE SUS TAREAS
d1.loc[(d1['FILTRO_C']==2)&
       (d1['PB3_11_1']=='NaN')&
       (d1['PB3_11_2']=='NaN')&
       (d1['PB3_11_3']=='NaN')&
       (d1['PB3_11_4']=='NaN')&
       (d1['PB3_11_5']=='NaN'),
       ['PB3_11_1','PB3_11_2','PB3_11_3','PB3_11_4','PB3_11_5']]=0

#MATERIALES QUE USA PARA SUS TAREAS
d1.loc[(d1['FILTRO_C']==2)&
       (d1['PB3_12_1']=='NaN')&
       (d1['PB3_12_2']=='NaN')&
       (d1['PB3_12_3']=='NaN')&
       (d1['PB3_12_4']=='NaN')&
       (d1['PB3_12_5']=='NaN')&
       (d1['PB3_12_6']=='NaN')&
       (d1['PB3_12_7']=='NaN')&
       (d1['PB3_12_8']=='NaN'),
       ['PB3_12_1','PB3_12_2','PB3_12_3','PB3_12_4','PB3_12_5','PB3_12_6','PB3_12_7','PB3_12_8']]=0

#¿LA PERSONA RECIBIO AYUDA de la familia?
d1.loc[(d1['FILTRO_C']==2) &
       (d1['PB3_13_1']=='NaN')&
       (d1['PB3_13_2']=='NaN')&
       (d1['PB3_13_3']=='NaN')&
       (d1['PB3_13_4']=='NaN')&
       (d1['PB3_13_5']=='NaN')&
       (d1['PB3_13_6']=='NaN')&
       (d1['PB3_13_7']=='NaN')&
       (d1['PB3_15']=='NaN')&
       (d1['PB3_14']=='NaN'),
       ['PB3_13_1','PB3_13_2','PB3_13_3','PB3_13_4','PB3_13_5','PB3_13_6','PB3_13_7','PB3_14','PB3_15']]=0

#¿cómo se siente de salud la persona?

d1.loc[(d1['FILTRO_C']==2)&
       (d1['PB3_16_1']=='NaN')&
       (d1['PB3_16_2']=='NaN')&
       (d1['PB3_16_3']=='NaN')&
       (d1['PB3_16_4']=='NaN')&
       (d1['PB3_16_5']=='NaN'),
       ['PB3_16_1','PB3_16_2','PB3_16_3','PB3_16_4','PB3_16_5']]=0


#d1.loc[(d1['PA3_4']==2)&(d1.loc[:,'PA3_8_1':'PA3_8_7']=='NaN'),'PA3_8_1':'PA3_8_7']=0
d1.drop(columns=['PA3_6','PA3_7_2','PA3_7_3','PA3_4','PB3_2','PC3_6'],inplace=True)
d2.drop(columns=['PA3_6','PA3_7_2','PA3_7_3','PA3_4','PB3_2','PC3_6'],inplace=True)
d1=d1.replace('NaN',np.nan)
d2=d2.replace('NaN',np.nan)
d1= d1.dropna(thresh=d1.shape[1]-5)
d2= d2.dropna(thresh=d2.shape[1]-5)
d1=d1.fillna(0)
d2=d2.fillna(0)
d1.to_csv('burrotes.csv')
print(d1.shape[0],d2.shape[0])




3365 8865
3364 7882


In [27]:
dfd=d1.append(d2)

C:\Users\52333\AppData\Local\Temp\ipykernel_9744\697421036.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dfd=d1.append(d2)


In [28]:
'''
import numpy as np

sum([True for idx,row in dfd.iterrows() if any(row.isnull())])
nans_count=dfd.isna().sum()
#print(nans_count)
#print(dfd.columns)
column_with_most_nans = np.argmax(nans_count)
print(column_with_most_nans)
print(dfd.columns[25])
print(nans_count[20])
'''

'\nimport numpy as np\n\nsum([True for idx,row in dfd.iterrows() if any(row.isnull())])\nnans_count=dfd.isna().sum()\n#print(nans_count)\n#print(dfd.columns)\ncolumn_with_most_nans = np.argmax(nans_count)\nprint(column_with_most_nans)\nprint(dfd.columns[25])\nprint(nans_count[20])\n'

In [29]:


dfd.to_csv('limpios.csv')

In [30]:
dfd.shape[0]

11246

In [31]:

import numpy as np
import pandas as pd
import random
from sklearn.neighbors import NearestNeighbors

In [32]:
def nearest_neighbour(x):
    nb=NearestNeighbors(n_neighbors=5,metric='euclidean',algorithm='kd_tree').fit(x)
    distancia,indices=nb.kneighbors(x)
    return indices
x = d1[d1.columns[3:]].to_numpy()
indices=nearest_neighbour(x)
print(indices)


[[   0 2958 1644 2995 1284]
 [   1 1882 3278 1496 1167]
 [   2  861  872 2803 1294]
 ...
 [3361 2468 1703 1629  187]
 [3362 2597 2873 1495 2931]
 [3363 1679 2409 1615  579]]


In [33]:
r=random.random()
r

0.09928788444346448

In [34]:
def SMOTE(x):
    rows=x.shape[0]
    indices=nearest_neighbour(x)
    new=[]
    for i in range (rows):
        mult=random.random()
        point_center=x[i,:]
        ind=np.random.randint(1,4)
        sx=int(indices[i,ind])
        second_point=x[sx,:]
        new_point=np.around(point_center+mult*(second_point-point_center))
        new.append(new_point)
    new=np.array(new)
    return new

new=SMOTE(x)
new


    

array([[3., 1., 2., ..., 5., 4., 0.],
       [1., 1., 1., ..., 0., 4., 0.],
       [1., 1., 1., ..., 5., 5., 0.],
       ...,
       [2., 1., 2., ..., 5., 5., 0.],
       [1., 1., 2., ..., 8., 4., 0.],
       [3., 1., 1., ..., 8., 5., 0.]])

In [35]:
print(x[:,1])

promedio_original=sum(x[:,90])/x.shape[1]
promedio_new=sum(new[:,90])/new.shape[1]
print(promedio_original,promedio_new)

[1. 1. 1. ... 1. 1. 1.]
827.1489361702128 827.4893617021277
